export const dataCars = 
  [
    {
      city_kml:12.2,
      price: 550,
      class:2500,
      combination_mpg:"y",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"solar",
      highway_mpg:31,
      make:"toyota",
      model:"innova reborn",
      transmission:"m",
      year:2017,
      link: 'https://www.youtube.com/',
      img: "/car-innova.png",
      img2: "/car-innova-1.png",
      img3: "/car-innova-2.png",
    },
    {
      city_kml:23,
      price: 350,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:31,
      make:"daihatsu",
      model:"xenia",
      transmission:"a",
      year:2022,
      link: 'https://www.youtube.com/',
      img: '/car-xenia.png',
      img2: '/car-xenia-1.png',
      img3: '/car-xenia-2.png',
    },
    {
      city_kml:23,
      price: 450,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:31,
      make:"nissan",
      model:"livina",
      transmission:"m",
      year:2016,
      link: 'https://www.youtube.com/',
      img: '/car-livina.png',
      img2: '/car-livina-1.png',
      img3: '/car-livina-2.png',
    },
    {
      city_kml:22,
      price: 550,
      class:2000,
      combination_mpg:"y",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"honda",
      model:"hrv",
      transmission:"m",
      year:2021,
      link: 'https://www.youtube.com/watch?v=tH9jV89Epvc',
      img: '/car-hrv.png',
      img2: '/car-hrv-1.png',
      img3: '/car-hrv-2.png',
    },
    {
      city_kml:12,
      price: 350,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"mitsubisi",
      model:"xpander",
      transmission:"a",
      year:2022,
      link: 'https://www.youtube.com/watch?v=tH9jV89Epvc',
      img: '/car-xpander.png',
      img2: '/car-xpander-1.png',
      img3: '/car-xpander-2.png',
    },
     {
      city_kml:12,
      price: 350,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"mitsubisi",
      model:"xpander",
      transmission:"a",
      year:2022,
      link: 'https://www.youtube.com/watch?v=tH9jV89Epvc',
      img: '/car-xpander.png',
      img2: '/car-xpander-1.png',
      img3: '/car-xpander-2.png',
    },
     {
      city_kml:12,
      price: 350,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"mitsubisi",
      model:"xpander",
      transmission:"a",
      year:2022,
      link: 'https://www.youtube.com/watch?v=tH9jV89Epvc',
      img: '/car-xpander.png',
      img2: '/car-xpander-1.png',
      img3: '/car-xpander-2.png',
    },
     {
      city_kml:12,
      price: 350,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"mitsubisi",
      model:"xpander",
      transmission:"a",
      year:2022,
      link: 'https://www.youtube.com/watch?v=tH9jV89Epvc',
      img: '/car-xpander.png',
      img2: '/car-xpander-1.png',
      img3: '/car-xpander-2.png',
    },
  ]
