export const dataCars = 
  [
    {
      city_kml:12.2,
      price: 650,
      class:2500,
      combination_mpg:"y",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"solar",
      highway_mpg:31,
      make:"toyota",
      model:"innova reborn",
      transmission:"a",
      year:2017,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Innova%20Reborn%20dong',
      img: "/car-innova.png",
      img2: "/car-innova-1.png",
      img3: "/car-innova-2.png",
    },
    {
      city_kml:13,
      price: 375,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:31,
      make:"daihatsu",
      model:"xenia",
      transmission:"a",
      year:2022,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Dihatsu%20Xenia%20dong',
      img: '/car-xenia.png',
      img2: '/car-xenia-1.png',
      img3: '/car-xenia-2.png',
    },
    {
      city_kml:10,
      price: 650,
      class:2500,
      combination_mpg:"y",
      cylinders:4,
      displacement:1.6,
      drive:"fwd",
      fuel_type:"solar",
      highway_mpg:31,
      make:"Mitsubisi",
      model:"Pajero",
      transmission:"a",
      year:2019,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Mitsubusi%20Pajero%20dong',
      img: '/car-pajero.png',
      img2: '/car-pajero-1.png',
      img3: '/car-pajero-2.png',
    },
    {
      city_kml:16.9,
      price: 250,
      class:1200,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"honda",
      model:"brio",
      transmission:"a",
      year:2021,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Honda%20Brio%20dong',
      img: '/car-brio.png',
      img2: '/car-brio-1.png',
      img3: '/car-brio-2.png',
    },
    {
      city_kml:12,
      price: 375,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"mitsubisi",
      model:"xpander",
      transmission:"a",
      year:2019,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Mitsubisi%20Xpander%20dong',
      img: '/car-xpander.png',
      img2: '/car-xpander-1.png',
      img3: '/car-xpander-2.png',
    },
     {
      city_kml:12,
      price: 375,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"daihatsu",
      model:"terios",
      transmission:"a",
      year:2022,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Daihatsu%20Terios%20dong',
      img: '/car-terios.png',
      img2: '/car-terios-1.png',
      img3: '/car-terios-2.png',
    },
     {
      city_kml:11.5,
      price: 275,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"toyota",
      model:"avanza",
      transmission:"m",
      year:2016,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Toyota%20Avanza%20dong',
      img: '/car-avanza.png',
      img2: '/car-avanza-1.png',
      img3: '/car-avanza-2.png',
    },
     {
      city_kml:14,
      price: 275,
      class:1200,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"daihatsu",
      model:"sigra",
      transmission:"m",
      year:2017,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Daihatsu%20Sigra%20dong',
      img: '/car-sigra.png',
      img2: '/car-sigra-1.png',
      img3: '/car-sigra-2.png',
    },
    {
      city_kml:10,
      price: 400,
      class:1500,
      combination_mpg:"n",
      cylinders:4,
      displacement:1.7,
      drive:"fwd",
      fuel_type:"bensin",
      highway_mpg:32,
      make:"honda",
      model:"jazz",
      transmission:"a",
      year:2017,
      link: 'https://api.whatsapp.com/send?phone=6281299090327&text=Halo%20Admin,%20mau%20cek%20ketersediaan%20mobil%20Honda%20Jazz%20dong',
      img: '/car-jazz.png',
      img2: '/car-jazz-1.png',
      img3: '/car-jazz-2.png',
    },
  ]

  export const testimoniData = 
  [
    {
      id: 1,
      name: 'Kevin Winata',
      content: 'Rental mobil Berkah Travel Trans sangat memuaskan! Pelayanan mereka sangat profesional dan ramah. Mobil yang disewakan dalam kondisi prima dan bersih. Saya sangat senang dengan pengalaman sewa mobil di sini. Terima kasih Berkah Travel Trans!',
      city: 'Kediri',
      rating: 5
    },
    {
      id: 2,
      name: 'Bayu Permadi',
      content: 'Saya sangat merekomendasikan Berkah Travel Trans untuk kebutuhan sewa mobil. Mereka memiliki berbagai pilihan mobil yang sesuai dengan kebutuhan dan budget saya. Pelayanan mereka sangat cepat dan responsif. Saya sangat puas dengan pengalaman menggunakan jasa sewa mobil dari Berkah Travel Trans.',
      city: 'Kediri',
      rating: 5
    },
    {
      id: 3,
      name: 'Setiawan Susilo',
      content: 'Berkah Travel Trans adalah pilihan terbaik untuk rental mobil. Harga sewa yang ditawarkan sangat terjangkau dan kompetitif. Mobil yang saya sewa dalam kondisi sangat baik dan nyaman untuk perjalanan jarak jauh. Layanan pelanggan mereka juga sangat baik dan membantu. Saya akan kembali menggunakan jasa mereka di masa mendatang.',
      city: 'Kediri',
      rating: 4
    },
    // {
    //   id: 4,
    //   name: 'Nanda Hamida',
    //   content: 'Saya sangat terkesan dengan layanan Berkah Travel Trans dalam hal sewa mobil. Mereka memberikan pilihan mobil yang sangat lengkap dan berkualitas. Pengambilan dan pengembalian mobil juga sangat mudah dan praktis. Saya merasa aman dan nyaman saat menggunakan mobil dari Berkah Travel Trans. Terima kasih atas pelayanannya yang luar biasa!',
    //   city: 'Kediri',
    //   rating: 4
    // },
    // {
    //   id: 5,
    //   name: 'Tata Sulysta',
    //   content: 'Saya ingin berbagi pengalaman menyenangkan saya menggunakan jasa sewa mobil dari Berkah Travel Trans. Staf mereka sangat profesional dan membantu dalam membantu saya memilih mobil yang sesuai dengan kebutuhan saya. Mobil yang saya sewa dalam kondisi prima dan nyaman untuk perjalanan panjang. Harga sewa juga sangat wajar. Saya sangat puas dengan layanan Berkah Travel Trans.',
    //   city: 'Kediri',
    //   rating: 5
    // },
    // {
    //   id: 6,
    //   name: 'Suyitno',
    //   content: 'Berkah Travel Trans adalah perusahaan sewa mobil terbaik yang pernah saya gunakan. Mereka memiliki armada mobil yang terawat dengan baik dan beragam pilihan mobil sesuai dengan kebutuhan. Pelayanan mereka sangat ramah dan responsif. Saya sangat merekomendasikan Berkah Travel Trans kepada siapa pun yang membutuhkan jasa sewa mobil yang handal.',
    //   city: 'Kediri',
    //   rating: 4
    // },
  ]